### ISSUE TITLE
Play claiming no actions are listed in task list.

### ISSUE THREAD

**Issue by oCroson** [robertdebock/ansible-role-nextcloud#5]
## Describe the bug

Role assumes there is no task/action being performed, there is obviously several actions that need to be taken and it is reading the tasks file well enough to see but i digress.

## Playbook
```yaml
---
- name: converge
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - role: ~/github/ansible-role-nextcloud
      nextcloud_apps:
        - name: richdocumentscode
      nextcloud_settings:
        - name: max_chunk_size
          section: files
          value: 0
```

```yaml
---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.core_dependencies
  - name: robertdebock.cron
  - name: robertdebock.epel
  - name: robertdebock.httpd
  - name: robertdebock.mysql
  - name: robertdebock.openssl
  - name: robertdebock.php
  - name: robertdebock.php_fpm
  - name: robertdebock.python_pip
  - name: robertdebock.redis
  - name: robertdebock.remi
  - name: robertdebock.selinux
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.mysql

```
## Output

tim@tim:~/github/ansible-role-nextcloud$ sudo ansible-playbook playbook.yml --ask-become-pass
SUDO password: 
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/tim/github/ansible-role-nextcloud/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Import assert.yml
  ^ here

## Environment

- Control node OS: Ubuntu 18.04 LTS
- Control node Ansible version: 2.5.1
- Managed node OS: Ubuntu 18.04 LTS
