### ISSUE TITLE
NextCloud role on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by dfranco** [robertdebock/ansible-role-nextcloud#6]
# Describe the bug

I'm trying to use this role on Debian 12, but get below error while running the playbook.

## Playbook

```yaml
---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.nextcloud
      nextcloud_apps:
        - name: richdocumentscode
      nextcloud_settings:
        - name: max_chunk_size
          section: files
          value: 0
```
I did used [these instructions](https://robertdebock.nl/how-to-use-these-roles.html) to prepare the host.

then I run

```shell
$ ansible-playbook playbook.yml -l my-host 
```

## Output

```
fatal: [nextcloud-server]: FAILED! => {"changed": true, "cmd": ["php", "occ", "maintenance:install", "--database", "mysql", "--database-name", "xxxxxxxx", "--database-user", "xxxxxxxx", "--database-pass", "xxxxxxxx", "--database-host", "xxxxxxxx", "--admin-user", "xxxxxxxx", "--admin-pass", "xxxxxxxx"], "delta": "0:00:00.044662", "end": "2024-09-02 06:05:07.661037", "msg": "non-zero return code", "rc": 1, "start": "2024-09-02 06:05:07.616375", "stderr": "", "stderr_lines": [], "stdout": "This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.20.", "stdout_lines": ["This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.20."]}
```

Content of `defaults/main.yml`

```yaml
nextcloud_version: "29.0.4"
```

## Environment

- Control node OS: MacOS Sonoma 14.6.1
- Control node Ansible version: 2.17.1
- Managed node OS: Debian 12 (bookworm)

Thanks for your help

Best,
